skyflowapi/skyflow-node

README.md, SECURITY.md
=> task/SDK-620/ Add SECURITY.md file and add security email in read me

.github/workflows/CI.yml, .github/workflows/master.yml, src/service-account/errors/Messages.ts, src/service-account/util/Token.ts, test/GenerateToken.test.js
=> SK-146/ Tokens with context and scoped token generation

src/index.js, src/service-account/errors/Messages.ts, src/service-account/util/Token.ts, src/vault-api/utils/logs.ts, test/GenerateToken.test.js
=> SK-147/ Add signed data token generation

CHANGELOG.md, README.md, samples/service-account/ScopedTokenGenerationExample.ts, samples/service-account/SignedTokenGenerationExample.ts, samples/service-account/TokenGenerationWithContextExample.ts
=> SK-149/ Add README, samples, changelog for CAA

README.md
=> SK-166/ Revert CAA and Upsert README changes

CHANGELOG.md, samples/service-account/SignedTokenGenerationExample.ts, samples/service-account/TokenGenerationWithContextExample.ts, src/service-account/util/Token.ts
=> SK-172/ Change context to "ctx" in CAA

.github/workflows/internal-release.yml
=> SK-221/ Add internal release for Node SDK

README.md
=> SK-237/ Update READ-ME with fixes

samples/vault-api/Get.ts, src/vault-api/Controller.ts, src/vault-api/Skyflow.ts, src/vault-api/utils/common/index.ts, src/vault-api/utils/constants.ts, src/vault-api/utils/logs.ts, src/vault-api/utils/validators/index.ts, test/vault-api/Skyflow.test.js
=> SK-276/ Deprecate GetByID method

package-lock.json, package.json
=> SK-285/ Bump jsonwebtoken from 8.5.1 to 9.0.0

samples/package-lock.json, samples/package.json
=> SK-285/ Fix dependabot alert in samples

package-lock.json, package.json, samples/package-lock.json
=> SK-308/ Update "jsonwebtoken" package to latest version

README.md, samples/vault-api/GetById.ts, src/vault-api/Controller.ts, src/vault-api/Skyflow.ts, src/vault-api/utils/common/index.ts, src/vault-api/utils/constants.ts, src/vault-api/utils/logs.ts, src/vault-api/utils/validators/index.ts, test/GenerateToken.test.js, test/vault-api/Skyflow.test.js
=> SK-298/ Separate get and getById methods

src/vault-api/utils/jwt-utils/index.ts
- Removed 5 mins of grace period for cache refresh of bearer token
- Issue [SK-547](https://skyflow.atlassian.net/browse/SK-547)
[SK-547]: https://skyflow.atlassian.net/browse/SK-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SK-547 Removal of Grace Period of 5 mins

CHANGELOG.md, README.md, samples/package.json, samples/vault-api/Delete.ts
- Updated README
- Updated CHANGELOG
- Added Sample for Delete by Skyflow ID in Node SDK
=> SK-860 Update README, CHANGELOG and Samples for Delete in Node SDK

package.json, src/vault-api/Controller.ts, src/vault-api/client/index.ts, src/vault-api/core/Collect.ts, src/vault-api/core/Delete.ts, src/vault-api/core/Reveal.ts, src/vault-api/utils/common/index.ts, src/vault-api/utils/constants.ts, src/vault-api/utils/logs.ts, test/vault-api/Client.test.js, test/vault-api/Skyflow.test.js
- SK-1316 Remove get call from batch Insert
- SK-1381 Public Release for `continueOnError` for batch Insert
=> SK-1381/Release/24.1.1

CHANGELOG.md, README.md, samples/package.json, samples/vault-api/InsertWithContinueOnError.ts
- SK-1370 Added README, CHANGELOG & Samples for continue on error support in batch insert
=> SK-1370 README, CHANGELOG and Samples

src/error/index.ts, src/vault/client/index.ts
- Why are you making the change?
Update error object structure
- What is the intended outcome?
Refined error structure
- How was the code tested?
Tested in local.
=> SK-1621: update error structure

package-lock.json
**Why**
The current Skyflow Node contains a few vulnerabilities that could lead to potential issues, such as security risks.
**Goal**
Enhance security by addressing the identified vulnerabilities.
=> SK-1807: Fix vulnerabilities

.github/workflows/CI.yml, .github/workflows/beta-release.yml, .github/workflows/common-ci.yml, .github/workflows/common-release.yml, .github/workflows/internal-release.yml, .github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/shared-build-and-deploy.yml
**Why**
- The current release pipelines for the Node SDK contain several repetitive steps within the workflows.
- These redundancies not only cause inefficiencies but also make it harder to maintain and debug the pipelines effectively.
**Goal**
- Reduced execution time by removing redundant steps.
- Creating reusable components will ensure that all workflows follow best practices and are easier to maintain moving forward.
=> SK-1819: Refactor release pipelines

README.md, src/vault/client/index.ts, src/vault/skyflow/index.ts, test/vault/client/client.test.js, test/vault/skyflow/skyflow.test.js
- To update the readme for Node SDK v2 
- Change the README to guide the users on v2 changes and migration from v1 to v2
- Define all the samples
=> SK-1895 update readme for node sdk v2

.github/workflows/Semgrep.yml
This workflow automatically runs Semgrep scans on pull requests to identify security vulnerabilities. All findings are displayed in the build log for review.
If any issues are detected, a comment is posted directly on the PR.
=> SC-5145:Create Semgrep.yml

.github/workflows/CI.yml, package.json, src/error/messages/index.ts, src/utils/validations/index.ts, src/vault/skyflow/index.ts, src/vault/types/index.ts, test/vault/skyflow/skyflow.test.js
- To fix insert call to accept int values
=> SK-2007: remove validations

package-lock.json, package.json
This PR updated the dependencies to latest stable versions.
- The versions for dependencies should be updated periodically.
- Up-to-date dependencies in the project.
=> SK-1927 Update dependencies to latest stable versions

README.md, samples/detect-api/deidentify-file.ts, samples/detect-api/deidentify-text.ts, samples/detect-api/get-detect-run.ts, samples/detect-api/reidentify-text.ts
**Why**
- Lack of a README and samples for the newly added "detect public interfaces" feature.
**Outcome**
- Provision of comprehensive samples and a README to facilitate the execution of the "detect public interfaces" functionality.
=> SK-2048: Add samples and update README for detect public interfaces.

test/vault/client/client.test.js, test/vault/controller/detect.test.js
**Why**
- Deidentify file test cases were failing.
**Outcome**
- Resolved failing test cases.
=> SK-2048:  Fix detect test cases.

.github/workflows/common-release.yml, package-lock.json, package.json, samples/package-lock.json
- To fix the vulnerabilities related to sha.js and axios
- There should be 0 critical vulnerabilities
=> SK-2328 public release after fixing vulnerabilities
